### PR TITLE
feat: reference OCaml implementation

### PR DESCRIPTION
**Pull request by titouancreach**
## Summary

Reference to my OCaml implementation.

### CODE REVIEW

**Comment by loreto** [comment]
Thanks @titouancreach!

Could you send me a link to your tests just to confirm they look good against the spec?

**Comment by titouancreach** [comment]
😬 do you have a set of tests ?

**Comment by loreto** [comment]
Yeah, so to mark things as 'Validated against spec', we've been asking implementations to pass these two sets of tests:
- https://github.com/jetpack-io/opensource/blob/main/typeid/typeid/spec/valid.yml
- https://github.com/jetpack-io/opensource/blob/main/typeid/typeid/spec/invalid.yml

For example, you can see the javascript implementation doing that here: https://github.com/jetpack-io/opensource/tree/main/typeid/typeid-js/test

If you don't have those tests yet, no worries. Just changed the validated column to 'Not Yet', and we can still go ahead and add your implementation to the list. We can switch from 'Not Yet', to 'Yes', once the tests are there.

**Comment by titouancreach** [comment]
Thanks for make it clear !

**Comment by titouancreach** [comment]
I implemented all the unit tests for both valid and invalid cases. You can check it here:
  - https://github.com/titouancreach/typeid-ocaml/blob/main/test/invalid_tests.ml 
  - https://github.com/titouancreach/typeid-ocaml/blob/main/test/valid_test.ml
  - https://github.com/titouancreach/typeid-ocaml/blob/main/test/test_typeid.ml

**Review by LucilleH — APPROVED** [review]
You have a typo here https://github.com/titouancreach/typeid-ocaml/blob/main/test/test_typeid.ml#L20 😄

**Comment by titouancreach** [comment]
thanks @LucilleH https://github.com/titouancreach/typeid-ocaml/commit/354fd7adaf5d21eafe3af06c98e6a69dc197998d

**Pull request merged**
