### PR TITLE
[envsec] Add info command and auto-switch orgs

### PR DESCRIPTION
**Pull request by mikeland73**
## Summary

This adds `envsec info` command that shows current project. It automatically detects the correct org.
We also now pick the correct credentials for the current project. This allows multiple credentials to work without having to re-log in.

## How was it tested?

`envsec info`
image

### CODE REVIEW

**Comment by loreto** [comment]
I know you asked for thoughts on this UX on slack .... I've been mulling on it. Assuming this is exposed to users, I think I'd prefer something like `envsec info` over `envsec projects current` (the last one feels awkward to me for some reason)

**Comment by mikeland73** [comment]
@loreto changed to `info` PTAL

**Comment by mikeland73** [comment]
I also added code to select the correct credentials for users that are logged in to multiple accounts.

**Review by loreto — APPROVED** [review]
LGTM

**Pull request merged**
