### PR TITLE
[easy][envsec] Fix env case

### PR DESCRIPTION
**Pull request by mikeland73**
## Summary

Not sure we wanna keep uppercase, but for now this needs to match the default.

### CODE REVIEW

**Comment by mohsenari** [comment]
@mikeland73 please see #118 when we use `envsec set` and other commands we lowercase the env name.

**Comment by ipince** [comment]
Also, FWIW, i prefer lowercase

**Comment by mikeland73** [comment]
@mohsenari https://github.com/jetpack-io/opensource/pull/118 is backwards incompatible. The bug you ran into is that the default flag for environment is `dev` but the default for everything else is `DEV`. This fixes that issue, but it doesn't change the flag values for now.

@ipince I agree lower case is better. We're just working out how to do it while continuing to support launchpad.

**Comment by mikeland73** [comment]
Closing in favor of https://github.com/jetpack-io/opensource/pull/118

**Pull request closed without merging**
